const productsContainer = document.getElementById("products"), title = document.getElementById("categoryTitle"), sortBox = document.getElementById("sortProducts"), searchInput = document.getElementById("getData");
let currentCategory = new URLSearchParams(location.search).get("category") || "all";
const categoryButtons = { all:"All Products", electronics:"Electronics", groceries:"Groceries", furniture:"Furniture", workers:"Manual Workers", building:"Building Materials" };
const esc = (value = "") => String(value).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const money = value => typeof formatPrice === "function" ? formatPrice(value) : "UGX " + Number(value).toLocaleString();
function createProductCard(item) { const worker = item.type === "worker", wished = !worker && JDKDiscovery.isWishlisted(item.id), pricing = !worker && window.JDKDeals ? JDKDeals.price(item) : { original:Number(item.price||0), final:Number(item.price||0), deal:null }; return `<article class="productCard${worker ? " workerCard" : ""}"><div class="imageContainer"><span class="discount">${worker ? "Available" : Number(item.stock || 0) > 0 ? "In stock" : "Sold out"}</span>${worker ? "" : `<button class="wishBtn${wished ? " active" : ""}" data-id="${esc(item.id)}">${wished ? "♥" : "♡"}</button>`}<img src="${esc(item.image)}" class="productImage" alt="${esc(item.name)}" loading="lazy"></div><div class="productInfo"><h3 class="productName">${esc(item.name)}</h3><p class="description">${esc(item.service || item.description || "Quality product from JDK Enterprises.")}</p>${worker ? '<div class="rating">★★★★★</div>' : `<div class="priceSection">${pricing.deal ? `<span class="saleBadge">${esc(JDKDeals.label(pricing.deal.promotion))}</span><span class="oldPrice">${money(pricing.original)}</span>` : ""}<span class="newPrice">${money(pricing.final)}</span></div>`}<button class="viewBtn" data-id="${esc(item.id)}">${worker ? "View Profile" : "View Details"}</button>${worker ? `<button class="contactWorkerBtn" data-phone="${esc(item.phone || "")}">Contact Worker</button>` : `<button class="cartBtn" data-id="${esc(item.id)}" ${Number(item.stock || 0) <= 0 ? "disabled" : ""}>${Number(item.stock || 0) > 0 ? "Add to Cart" : "Out of Stock"}</button>`}</div></article>`; }
function updateActiveCategory() { document.querySelectorAll(".categoryBtn, .li").forEach(button => button.classList.remove("active")); document.getElementById(currentCategory)?.classList.add("active"); document.querySelector(`.categoryBtn[data-category="${currentCategory}"]`)?.classList.add("active"); if (title) title.textContent = categoryButtons[currentCategory] || "Marketplace"; }
function displayProducts() { if (!productsContainer) return; let list = JDKStore.items.filter(item => currentCategory === "all" || item.category === currentCategory); list = JDKDiscovery.search(list, searchInput?.value || ""); if (sortBox?.value === "low") list.sort((a,b)=>(a.price||0)-(b.price||0)); if (sortBox?.value === "high") list.sort((a,b)=>(b.price||0)-(a.price||0)); productsContainer.innerHTML = list.length ? list.map(createProductCard).join("") : '<div class="emptyProducts"><h3>No items found</h3><p>Try another category or search.</p></div>'; bind(); updateActiveCategory(); }
function bind() { document.querySelectorAll(".cartBtn").forEach(button => button.onclick = () => { const item = JDKStore.findItem(button.dataset.id); if (JDKStore.addToCart(item)) JDKUI.notify(item.name + " added to cart"); else JDKUI.notify("Stock limit reached", "warning"); }); document.querySelectorAll(".viewBtn").forEach(button => button.onclick = () => { const item = JDKStore.findItem(button.dataset.id); JDKStore.selectItem(item); JDKDiscovery.recordView(item); location.href = "product.html"; }); document.querySelectorAll(".wishBtn").forEach(button => button.onclick = () => { const item = JDKStore.findItem(button.dataset.id); JDKDiscovery.toggleWishlist(item); displayProducts(); }); document.querySelectorAll(".contactWorkerBtn").forEach(button => button.onclick = () => button.dataset.phone ? location.href = "tel:" + button.dataset.phone : JDKUI.notify("Phone number unavailable", "warning")); }
Object.entries(categoryButtons).forEach(([id]) => document.getElementById(id)?.addEventListener("click", () => { currentCategory = id; history.replaceState(null, "", `categories.html?category=${id}`); displayProducts(); })); document.querySelectorAll(".categoryBtn").forEach(button => button.addEventListener("click", () => { currentCategory = button.dataset.category || "all"; displayProducts(); })); sortBox?.addEventListener("change", displayProducts); searchInput?.addEventListener("input", displayProducts); document.getElementById("submitSearch")?.addEventListener("click", displayProducts); window.addEventListener("jdk:catalog-ready", displayProducts); displayProducts();

window.addEventListener("jdk:deals-ready", renderProducts);
